<a href="https://colab.research.google.com/github/mazhar75/Algorithms/blob/master/security.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TASK 01 : Ceaser Cipher

##a) Implement the Decryption part of Caesar Cipher which will take a key and a ciphertext as inputs and give a plaintext as output.

In [1]:
def Ceasar_Cipher_Decryption(key, text):
    decrypted_text = ""
    for char in text:
        if char.isupper():
            decrypted_text += chr((ord(char) - key - 65) % 26 + 65)
        elif char.islower():
            decrypted_text += chr((ord(char) - key - 97) % 26 + 97)
        else:
            decrypted_text += char
    return decrypted_text

# Test the function
s = "Mazharul Islam"
print(Ceasar_Cipher_Decryption(2, s))


Kyxfypsj Gqjyk


##b)  Use the above code to crack the following Caesar ciphertext, to identify the text encrypted: "XNZ XVMIDQVG VO DDXO WPDGYDIB NPNO DN BJDIB OJ WZ BMZVO VBVDI".

In [2]:
encrypted_text="XNZ XVMIDQVG VO DDXO WPDGYDIB NPNO DN BJDIB OJ WZ BMZVO VBVDI"
for i in range(26):
  print("when key = ",i)
  print(Ceasar_Cipher_Decryption(i,encrypted_text))


when key =  0
XNZ XVMIDQVG VO DDXO WPDGYDIB NPNO DN BJDIB OJ WZ BMZVO VBVDI
when key =  1
WMY WULHCPUF UN CCWN VOCFXCHA MOMN CM AICHA NI VY ALYUN UAUCH
when key =  2
VLX VTKGBOTE TM BBVM UNBEWBGZ LNLM BL ZHBGZ MH UX ZKXTM TZTBG
when key =  3
UKW USJFANSD SL AAUL TMADVAFY KMKL AK YGAFY LG TW YJWSL SYSAF
when key =  4
TJV TRIEZMRC RK ZZTK SLZCUZEX JLJK ZJ XFZEX KF SV XIVRK RXRZE
when key =  5
SIU SQHDYLQB QJ YYSJ RKYBTYDW IKIJ YI WEYDW JE RU WHUQJ QWQYD
when key =  6
RHT RPGCXKPA PI XXRI QJXASXCV HJHI XH VDXCV ID QT VGTPI PVPXC
when key =  7
QGS QOFBWJOZ OH WWQH PIWZRWBU GIGH WG UCWBU HC PS UFSOH OUOWB
when key =  8
PFR PNEAVINY NG VVPG OHVYQVAT FHFG VF TBVAT GB OR TERNG NTNVA
when key =  9
OEQ OMDZUHMX MF UUOF NGUXPUZS EGEF UE SAUZS FA NQ SDQMF MSMUZ
when key =  10
NDP NLCYTGLW LE TTNE MFTWOTYR DFDE TD RZTYR EZ MP RCPLE LRLTY
when key =  11
MCO MKBXSFKV KD SSMD LESVNSXQ CECD SC QYSXQ DY LO QBOKD KQKSX
when key =  12
LBN LJAWREJU JC RRLC KDRUMRWP BDBC RB PXRWP CX KN PANJC JPJRW
when key 

##C) Use the above code to decode these messages, which were encoded using the same Caesar cipher (among these 03 cipher blocks) and fill up the boxes.





In [3]:
block1="ZKDW GR BRX JHW ZKHQ BRX"
block2="FURVV D VQRZPDQ ZLWK D"
block3="YDPSLUH? IURVWELWH"
for i in range(26):
  print("when key = ",i)
  print(Ceasar_Cipher_Decryption(i,block1))
  print(Ceasar_Cipher_Decryption(i,block2))
  print(Ceasar_Cipher_Decryption(i,block3))
  print("")


when key =  0
ZKDW GR BRX JHW ZKHQ BRX
FURVV D VQRZPDQ ZLWK D
YDPSLUH? IURVWELWH

when key =  1
YJCV FQ AQW IGV YJGP AQW
ETQUU C UPQYOCP YKVJ C
XCORKTG? HTQUVDKVG

when key =  2
XIBU EP ZPV HFU XIFO ZPV
DSPTT B TOPXNBO XJUI B
WBNQJSF? GSPTUCJUF

when key =  3
WHAT DO YOU GET WHEN YOU
CROSS A SNOWMAN WITH A
VAMPIRE? FROSTBITE

when key =  4
VGZS CN XNT FDS VGDM XNT
BQNRR Z RMNVLZM VHSG Z
UZLOHQD? EQNRSAHSD

when key =  5
UFYR BM WMS ECR UFCL WMS
APMQQ Y QLMUKYL UGRF Y
TYKNGPC? DPMQRZGRC

when key =  6
TEXQ AL VLR DBQ TEBK VLR
ZOLPP X PKLTJXK TFQE X
SXJMFOB? COLPQYFQB

when key =  7
SDWP ZK UKQ CAP SDAJ UKQ
YNKOO W OJKSIWJ SEPD W
RWILENA? BNKOPXEPA

when key =  8
RCVO YJ TJP BZO RCZI TJP
XMJNN V NIJRHVI RDOC V
QVHKDMZ? AMJNOWDOZ

when key =  9
QBUN XI SIO AYN QBYH SIO
WLIMM U MHIQGUH QCNB U
PUGJCLY? ZLIMNVCNY

when key =  10
PATM WH RHN ZXM PAXG RHN
VKHLL T LGHPFTG PBMA T
OTFIBKX? YKHLMUBMX

when key =  11
OZSL VG QGM YWL OZWF QGM
UJGKK S KFGOESF OALZ S
NSEHAJW? XJGKLTALW

when key =  12

#TASK 02 : Substitution Cipher

In [4]:
from collections import Counter
def display_mapping(text, mapping, words_per_line):
    n=len(text)
    pairs = mapping.split()
    mapping_dict = {}
    for pair in pairs:
        key, value = pair.split(':')
        mapping_dict[key] = value
    res=""
    for i in range(n):
      if 'a' <= text[i] <= 'z':
           if text[i] in mapping_dict:
              res += mapping_dict[text[i]]
           else:
              res += '*'
      elif 'A'<= text[i] <='Z':
           if text[i] in mapping_dict:
              res += mapping_dict[text[i]]
           else:
              res += '*'
      else:
           res += text[i]
    words = text.split()
    cipher=res.split()
    for i in range(0, len(words), words_per_line):
        print(' '.join(words[i:i+words_per_line]))
    print(" ")
    for i in range(0, len(cipher), words_per_line):
        print(' '.join(cipher[i:i+words_per_line]))
def freq_analyze(text):
  res=Counter(text)
  return sorted(res.items(), key=lambda x: x[1], reverse=True)


 ***a) Encrypted message :***  gtd bsvgl vf fgedsugt dffml dkcymvsf gtmg gtd chjde ha aevdsxftvc tdycf
bf gh id fgehsu aehz tmexftvcf. aevdsxf qms uvod bf gtd fgedsugt jd sddx
jtds yvad udgf ghbut. vs mxxvgvhs, cdhcyd dkcedff bsvgl gtehbut
yhod,amzvyl, aevdsxf, msx hgtdef ftmed fghevdf ha avsxvsu qhzzhs
uehbsx jvgt fhzdhsd.gtded med zmsl idsdavgf ha fgmlvsu bsvgdx vs
ghbut gvzdf, mf vg tdycf gh amqd qtmyydsuvsu fvgbmgvhsf jvgt
qhbemud. gtd vzchegmsqd ha fgmlvsu bsvgdx tmf fgebqp m qthex mzhsu
zmsl cdhcyd gtehbuthbg tvfghel.pddcvsu zdzhevdf ha jtmg jd tmod
mqqhzcyvftdx gtehbuthbg tvfghel qms tdyc bf fdd thj vsxvovxbmyf msx
qhzzbsvgvdf tmod cdefdodedx gtehbut ghbut gvzdf msx vsgh m ievutgde
abgbed.

In [5]:
text = "gtd bsvgl vf fgedsugt dffml dkcymvsf gtmg gtd chjde ha aevdsxftvc tdycf \
bf gh id fgehsu aehz tmexftvcf. aevdsxf qms uvod bf gtd fgedsugt jd sddx \
jtds yvad udgf ghbut. vs mxxvgvhs, cdhcyd dkcedff bsvgl gtehbut \
yhod,amzvyl, aevdsxf, msx hgtdef ftmed fghevdf ha avsxvsu qhzzhs \
uehbsx jvgt fhzdhsd.gtded med zmsl idsdavgf ha fgmlvsu bsvgdx vs \
ghbut gvzdf, mf vg tdycf gh amqd qtmyydsuvsu fvgbmgvhsf jvgt \
qhbemud. gtd vzchegmsqd ha fgmlvsu bsvgdx tmf fgebqp m qthex mzhsu \
zmsl cdhcyd gtehbuthbg tvfghel.pddcvsu zdzhevdf ha jtmg jd tmod \
mqqhzcyvftdx gtehbuthbg tvfghel qms tdyc bf fdd thj vsxvovxbmyf msx \
qhzzbsvgvdf tmod cdefdodedx gtehbut ghbut gvzdf msx vsgh m ievutgde \
abgbed."
mapping = "d:e g:t t:h m:a v:i f:s l:y e:r h:o s:n u:g b:u z:m q:c c:p a:f y:l x:d o:v i:b p:k k:x j:w"
words_per_line = 10
display_mapping(text, mapping, words_per_line)


gtd bsvgl vf fgedsugt dffml dkcymvsf gtmg gtd chjde ha
aevdsxftvc tdycf bf gh id fgehsu aehz tmexftvcf. aevdsxf qms
uvod bf gtd fgedsugt jd sddx jtds yvad udgf ghbut.
vs mxxvgvhs, cdhcyd dkcedff bsvgl gtehbut yhod,amzvyl, aevdsxf, msx hgtdef
ftmed fghevdf ha avsxvsu qhzzhs uehbsx jvgt fhzdhsd.gtded med zmsl
idsdavgf ha fgmlvsu bsvgdx vs ghbut gvzdf, mf vg tdycf
gh amqd qtmyydsuvsu fvgbmgvhsf jvgt qhbemud. gtd vzchegmsqd ha fgmlvsu
bsvgdx tmf fgebqp m qthex mzhsu zmsl cdhcyd gtehbuthbg tvfghel.pddcvsu
zdzhevdf ha jtmg jd tmod mqqhzcyvftdx gtehbuthbg tvfghel qms tdyc
bf fdd thj vsxvovxbmyf msx qhzzbsvgvdf tmod cdefdodedx gtehbut ghbut
gvzdf msx vsgh m ievutgde abgbed.
 
the unity is strength essay explains that the power of
friendship helps us to be strong from hardships. friends can
give us the strength we need when life gets tough.
in addition, people express unity through love,family, friends, and others
share stories of finding common ground with someone.there are many
benefits of st

***b) Encrypted message :*** exupziu kxwqxagxom, upm gxsm zs l amtwzo exgg rmqzfm kigg
lok xolquxjm.lgwz, l kxwqxagxomk amtwzo qlo qzoutzg lok plokgm
upm wxuiluxzo zs gxjxoh xo l wzapxwuxqlumk elc uplo upzwm epz
kz ozu.fztmzjmt, xs czi pljm l aglo lok czi elou
uz xfagmfmou xu xo czit gxsm upmo czi ommk kxwqxagxom.
xu flnmw upxohw mlwc szt czi uz plokgm lok iguxflumgc
rtxoh wiqqmww uz czit gxsm.xs ulgn lrziu upm ucamw zs
kxwqxagxom, upmo upmc ltm hmomtlggc zs uez ucamw. sxtwu zom
xw xokiqmk kxwqxagxom lok upm wmqzok zom xw wmgs-
kxwqxagxom.xokiqmk kxwqxagxom
xw wzfmupxoh uplu zupmtw ulihpu iw zt em gmlto rc
wmmxoh zupmtw. epxgm wmgs-kxwqxagxom qzfmw stzf exupxo lok
em gmlto xu zo zit zeo wmgs. wmgs-kxwqxagxom tmyixtmw l gzu
zs fzuxjluxzo lok wiaaztu stzf zupmtw.lrzjm lgg, szggzexoh czit klxgc
wqpmkigm exupziu loc fxwulnm xw lgwz altu zs rmxoh kxwqxagxomk.

In [6]:
text_b="exupziu kxwqxagxom, upm gxsm zs l amtwzo exgg rmqzfm kigg \
lok xolquxjm.lgwz, l kxwqxagxomk amtwzo qlo qzoutzg lok plokgm \
upm wxuiluxzo zs gxjxoh xo l wzapxwuxqlumk elc uplo upzwm epz \
kz ozu.fztmzjmt, xs czi pljm l aglo lok czi elou \
uz xfagmfmou xu xo czit gxsm upmo czi ommk kxwqxagxom. \
xu flnmw upxohw mlwc szt czi uz plokgm lok iguxflumgc \
rtxoh wiqqmww uz czit gxsm.xs ulgn lrziu upm ucamw zs \
kxwqxagxom, upmo upmc ltm hmomtlggc zs uez ucamw. sxtwu zom \
xw xokiqmk kxwqxagxom lok upm wmqzok zom xw wmgs- \
kxwqxagxom.xokiqmk kxwqxagxom \
xw wzfmupxoh uplu zupmtw ulihpu iw zt em gmlto rc \
wmmxoh zupmtw. epxgm wmgs-kxwqxagxom qzfmw stzf exupxo lok \
em gmlto xu zo zit zeo wmgs. wmgs-kxwqxagxom tmyixtmw l gzu \
zs fzuxjluxzo lok wiaaztu stzf zupmtw.lrzjm lgg, szggzexoh czit klxgc \
wqpmkigm exupziu loc fxwulnm xw lgwz altu zs rmxoh kxwqxagxomk."

mapping = "l:a o:n k:d x:i m:e z:o w:s q:c a:p g:l s:f t:r e:w c:y u:t i:u p:h h:g f:m r:b j:v n:k y:q"
words_per_line = 10
display_mapping(text_b, mapping, words_per_line)

exupziu kxwqxagxom, upm gxsm zs l amtwzo exgg rmqzfm kigg
lok xolquxjm.lgwz, l kxwqxagxomk amtwzo qlo qzoutzg lok plokgm upm
wxuiluxzo zs gxjxoh xo l wzapxwuxqlumk elc uplo upzwm epz
kz ozu.fztmzjmt, xs czi pljm l aglo lok czi elou
uz xfagmfmou xu xo czit gxsm upmo czi ommk kxwqxagxom.
xu flnmw upxohw mlwc szt czi uz plokgm lok iguxflumgc
rtxoh wiqqmww uz czit gxsm.xs ulgn lrziu upm ucamw zs
kxwqxagxom, upmo upmc ltm hmomtlggc zs uez ucamw. sxtwu zom
xw xokiqmk kxwqxagxom lok upm wmqzok zom xw wmgs- kxwqxagxom.xokiqmk
kxwqxagxom xw wzfmupxoh uplu zupmtw ulihpu iw zt em gmlto
rc wmmxoh zupmtw. epxgm wmgs-kxwqxagxom qzfmw stzf exupxo lok em
gmlto xu zo zit zeo wmgs. wmgs-kxwqxagxom tmyixtmw l gzu
zs fzuxjluxzo lok wiaaztu stzf zupmtw.lrzjm lgg, szggzexoh czit klxgc
wqpmkigm exupziu loc fxwulnm xw lgwz altu zs rmxoh kxwqxagxomk.
 
without discipline, the life of a person will become dull
and inactive.also, a disciplined person can control and handle the
situation of living in a sophistica

***c) Encrypted message :*** AUHC MVKFC V BYZUGC V IZMC CJ GUMBZYAZD UKUVM.
VC HZZGZB CJ GZ, V HCJJB PD CFZ VYJM KUCZ AZUBVMK CJ CFZ
BYVWZ UMB OJY U IFVAZ, V TJNAB MJC ZMCZY.
OJY CFZ IUD, VC IUH PUYYZB CJ GZ.

In [7]:
text_c = "AUHC MVKFC V BYZUGC V IZMC CJ GUMBZYAZD UKUVM. \
VC HZZGZB CJ GZ, V HCJJB PD CFZ VYJM KUCZ AZUBVMK CJ CFZ \
BYVWZ UMB OJY U IFVAZ, V TJNAB MJC ZMCZY. \
OJY CFZ IUD, VC IUH PUYYZB CJ GZ."
mapping_c ="V:I Z:E C:T F:H J:O M:N K:G Y:R G:M O:F I:W U:A T:C N:U A:L B:D H:S D:Y P:B W:V"
words_per_line = 10
display_mapping(text_c, mapping_c, words_per_line)

AUHC MVKFC V BYZUGC V IZMC CJ GUMBZYAZD UKUVM. VC
HZZGZB CJ GZ, V HCJJB PD CFZ VYJM KUCZ AZUBVMK
CJ CFZ BYVWZ UMB OJY U IFVAZ, V TJNAB MJC
ZMCZY. OJY CFZ IUD, VC IUH PUYYZB CJ GZ.
 
LAST NIGHT I DREAMT I WENT TO MANDERLEY AGAIN. IT
SEEMED TO ME, I STOOD BY THE IRON GATE LEADING
TO THE DRIVE AND FOR A WHILE, I COULD NOT
ENTER. FOR THE WAY, IT WAS BARRED TO ME.


***d) Encrypted message :*** JGRMQOYGHMVBJ WRWQFPW HGF FDQGFPFZR KBEEBJIZQ QO CIBZK.
LFAFGQVFZFWW, EOG WOPF GFHWOL PHLR LOLFDMFGQW BLWBWQ OL
KFWBYLBLY LFS FLJGRMQBOL WJVFPFW QVHQ WFFP QO QVFP QO CF
POGF WFJIGF QVHL HLR OQVFG WJVFPF OL FHGQV. QVF ILEOGQILHQF
QGIQV VOSFAFG BW QVHQ WIJV WJVFPFW HGF IWIHZZR QGBABHZ QO
CGFHX.

In [8]:
text_d = "JGRMQOYGHMVBJ WRWQFPW HGF FDQGFPFZR KBEEBJIZQ QO CIBZK. \
LFAFGQVFZFWW, EOG WOPF GFHWOL PHLR LOLFDMFGQW BLWBWQ OL \
KFWBYLBLY LFS FLJGRMQBOL WJVFPFW QVHQ WFFP QO QVFP QO CF \
POGF WFJIGF QVHL HLR OQVFG WJVFPF OL FHGQV. QVF ILEOGQILHQF \
QGIQV VOSFAFG BW QVHQ WIJV WJVFPFW HGF IWIHZZR QGBABHZ QO \
CGFHX."
mapping_d ="F:E C:B Q:T V:H H:A P:M O:O L:N G:R I:U W:S J:C R:Y E:F D:X Z:L K:D B:I A:V M:P Y:G S:W X:K"
words_per_line = 10
display_mapping(text_d, mapping_d, words_per_line)

JGRMQOYGHMVBJ WRWQFPW HGF FDQGFPFZR KBEEBJIZQ QO CIBZK. LFAFGQVFZFWW, EOG WOPF
GFHWOL PHLR LOLFDMFGQW BLWBWQ OL KFWBYLBLY LFS FLJGRMQBOL WJVFPFW QVHQ
WFFP QO QVFP QO CF POGF WFJIGF QVHL HLR OQVFG
WJVFPF OL FHGQV. QVF ILEOGQILHQF QGIQV VOSFAFG BW QVHQ WIJV
WJVFPFW HGF IWIHZZR QGBABHZ QO CGFHX.
 
CRYPTOGRAPHIC SYSTEMS ARE EXTREMELY DIFFICULT TO BUILD. NEVERTHELESS, FOR SOME
REASON MANY NONEXPERTS INSIST ON DESIGNING NEW ENCRYPTION SCHEMES THAT
SEEM TO THEM TO BE MORE SECURE THAN ANY OTHER
SCHEME ON EARTH. THE UNFORTUNATE TRUTH HOWEVER IS THAT SUCH
SCHEMES ARE USUALLY TRIVIAL TO BREAK.


In [9]:
freq_analyze(text_d)

[(' ', 45),
 ('F', 37),
 ('Q', 26),
 ('W', 21),
 ('G', 19),
 ('L', 17),
 ('O', 16),
 ('V', 15),
 ('H', 14),
 ('B', 12),
 ('P', 10),
 ('J', 9),
 ('I', 9),
 ('R', 7),
 ('Z', 7),
 ('M', 4),
 ('E', 4),
 ('Y', 3),
 ('K', 3),
 ('C', 3),
 ('.', 3),
 ('A', 3),
 ('D', 2),
 ('S', 2),
 (',', 1),
 ('X', 1)]

#TASK 03:Vignere crypto

In [10]:
def Vignere_Encryption(text,key):
  n=len(text)
  m=len(key)
  mapping=""
  ind=0
  for i in range(n):
    if 'a'<=text[i]<='z':
      mapping += key[ind]
      ind=ind+1
    elif 'A'<=text[i]<='Z':
      mapping += key[ind]
      ind=ind+1
    else:
      mapping += text[i]
    ind=ind%m
  decrypted_text=""
  for i in range(n):
    if 'a'<=text[i]<='z':
      decrypted_text += chr((ord(text[i])-97+ord(mapping[i])-97)%26+97)
    elif 'A'<=text[i]<='Z':
      decrypted_text += chr((ord(text[i])-65+ord(mapping[i])-65)%26+65)
    else:
      decrypted_text += text[i]
  return decrypted_text

def Vignere_Decryption(text,key):
  n=len(text)
  m=len(key)
  mapping=""
  ind=0
  for i in range(n):
    if 'a'<=text[i]<='z':
      mapping += key[ind]
      ind=ind+1
    elif 'A'<=text[i]<='Z':
      mapping += key[ind]
      ind=ind+1
    else:
      mapping += text[i]
    ind=ind%m
  decrypted_text=""
  for i in range(n):
    if 'a'<=text[i]<='z':
      decrypted_text += chr((ord(text[i])-97-ord(mapping[i])-97)%26+97)
    elif 'A'<=text[i]<='Z':
      decrypted_text += chr((ord(text[i])-65-ord(mapping[i])-65)%26+65)
    else:
      decrypted_text += text[i]
  return decrypted_text
print("Welcome to Vignere Crypto System !")
while 1:
  text = input("Enter Your Cipher Here : ")
  key = input("Enter your key here : ")
  choice=int(input("For Encryption type 1 and for decryption type 2 : "))
  if choice==1:
    msg = Vignere_Encryption(text,key)
    print("Your Cipher :")
    print(text)
    print("Encrypted msg :")
    print(msg)
  else :
    msg=Vignere_Decryption(text,key)
    print("Your Cipher :")
    print(text)
    print("Dncrypted msg :")
    print(msg)
  print("To quit type 0 ")
  q=int(input())
  if q==0:
    break

Welcome to Vignere Crypto System !
Enter Your Cipher Here : hello
Enter your key here : hi
For Encryption type 1 and for decryption type 2 : 1
Your Cipher :
hello
Encrypted msg :
omstv
To quit type 0 
0


#TASK 04:HILL CIPHER

In [11]:
def decrypt(ciphertext, key_matrix):
    # Remove spaces and convert to uppercase
    ciphertext = ciphertext.replace(" ", "").upper()

    # Convert characters to numbers
    ciphertext_numbers = np.array([ord(char) - ord('A') for char in ciphertext])

    # Determine the size of the key matrix
    n = key_matrix.shape[0]

    # Calculate the determinant of the key matrix
    det = int(np.round(np.linalg.det(key_matrix)))

    # Calculate the inverse of the key matrix
    inv_key_matrix = np.linalg.inv(key_matrix)

    # Calculate the modular inverse of the determinant
    det_inv = None
    for i in range(26):
        if (det * i) % 26 == 1:
            det_inv = i
            break

    if det_inv is None:
        raise ValueError("Determinant has no modular inverse (not relatively prime with 26)")

    # Calculate the adjugate of the key matrix
    adj_key_matrix = (det * inv_key_matrix) % 26

    # Multiply the adjugate by the modular inverse of the determinant
    inv_key_matrix_mod26 = (det_inv * adj_key_matrix) % 26

    # Perform decryption: multiply the inverse key matrix with the ciphertext matrix
    plaintext_numbers = np.dot(inv_key_matrix_mod26, ciphertext_numbers) % 26

    # Ensure all numbers are within the range 0-25
    plaintext_numbers = np.mod(plaintext_numbers.astype(int), 26)

    # Convert numbers back to characters
    plaintext = "".join([chr(num + ord('A')) for num in plaintext_numbers])

    return plaintext


In [12]:
import numpy as np

# Function to generate the key matrix from the provided key
def generate_key_matrix(key):
    # Remove spaces from the key
    key = key.replace(" ", "")
    # Calculate the size of the key matrix (it's a square matrix)
    n = int(np.sqrt(len(key)))
    # Convert the key string to numbers (A=0, B=1, ..., Z=25)
    key_matrix = np.array([ord(char) - ord('A') for char in key])
    # Resize the key matrix to the appropriate size
    key_matrix.resize((n, n))
    # Print the key matrix (optional)
    print(key_matrix)
    return key_matrix

# Function to encrypt plaintext using the provided key matrix
def encrypt(plaintext, key_matrix):

    plaintext = plaintext.replace(" ", "").upper()
    # Determine the size of the key matrix (number of rows/columns)
    n = key_matrix.shape[0]
    # Add padding to the plaintext if necessary to make it divisible by the size of the key matrix
    if len(plaintext) % n != 0:
        plaintext += 'X' * (n - len(plaintext) % n)

    ciphertext = ""
    # Encrypt the plaintext block by block

    for i in range(0, len(plaintext), n):
        # Extract a block of plaintext characters

        block = np.array([ord(char) - ord('A') for char in plaintext[i:i+n]])
        # Resize the block to a column vector

        block.resize((n, 1))
        # Perform encryption: multiply the key matrix with the plaintext block and take modulo 26

        encrypted_block = np.dot(key_matrix, block) % 26
        # Convert the encrypted block back to characters

        ciphertext += ''.join([chr(char + ord('A')) for char in encrypted_block.flatten()])
    return ciphertext


# Sample key
key = "THIS IS MD MAZHARUL ISLAM NIHAD FROM SUST CSE"
key_matrix = generate_key_matrix(key)

# Ask user for operation
operation = input("Enter 'E' for encryption or 'D' for decryption: ").upper()

if operation == 'E':
    plaintext = input("Enter the plaintext: ")
    print("Ciphertext:", encrypt(plaintext, key_matrix))
elif operation == 'D':
    plaintext = input("Enter the plaintext: ")
    print("Ciphertext:", decrypt(plaintext, key_matrix))
else:
    print("Invalid operation. Please enter 'E' or 'D' for encryption or decryption.")

[[19  7  8 18  8 18]
 [12  3 12  0 25  7]
 [ 0 17 20 11  8 18]
 [11  0 12 13  8  7]
 [ 0  3  5 17 14 12]
 [18 20 18 19  2 18]]
Enter 'E' for encryption or 'D' for decryption: E
Enter the plaintext: hello
Ciphertext: LLZBYP


In [13]:
# Sample key
key = "THIS IS MD MAZHARUL ISLAM NIHAD FROM SUST CSE"
key_matrix = generate_key_matrix(key)

# Ask user for operation
operation = input("Enter 'E' for encryption or 'D' for decryption: ").upper()

if operation == 'E':
    plaintext = input("Enter the plaintext: ")
    print("Ciphertext:", encrypt(plaintext, key_matrix))
elif operation == 'D':
    plaintext = input("Enter the plaintext: ")
    print("Ciphertext:", decrypt(plaintext, key_matrix))
else:
    print("Invalid operation. Please enter 'E' or 'D' for encryption or decryption.")

[[19  7  8 18  8 18]
 [12  3 12  0 25  7]
 [ 0 17 20 11  8 18]
 [11  0 12 13  8  7]
 [ 0  3  5 17 14 12]
 [18 20 18 19  2 18]]
Enter 'E' for encryption or 'D' for decryption: E
Enter the plaintext: HELLO
Ciphertext: LLZBYP
